routes/web.php
<?php

use App\Http\Middleware\Authenticate;
use App\Monuments\Contacts\Controllers\Admin\ContactController;
use App\Monuments\Gallery\Controllers\Admin\GalleryController;
use App\Monuments\Reviews\Controllers\Admin\ReviewsController;
use App\Monuments\Services\Controllers\Admin\ServicesController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/admin', [App\Http\Controllers\HomeController::class, 'index'])->name('admin');

Route::middleware(Authenticate::class)
    ->name('admin.')
    ->prefix('admin')
    ->group(function () {
        Route::name('contact.')->prefix('contact')->group(function () {
            Route::get('/', [ContactController::class, 'index'])->name('index');
            Route::post('/', [ContactController::class, 'store'])->name('store');
            Route::get('/{id}', [ContactController::class, 'show'])->name('show');
            Route::put('/{id}', [ContactController::class, 'update'])->name('update');
            Route::delete('/{id}', [ContactController::class, 'delete'])->name('delete');
        });
        Route::name('services.')->prefix('services')->group(function () {
            Route::get('/', [ServicesController::class, 'index'])->name('index');
            Route::post('/', [ServicesController::class, 'store'])->name('store');
            Route::get('/{id}', [ServicesController::class, 'show'])->name('show');
            Route::put('/{id}', [ServicesController::class, 'update'])->name('update');
            Route::delete('/{id}', [ServicesController::class, 'delete'])->name('delete');
        });
        Route::name('gallery.')->prefix('gallery')->group(function () {
            Route::get('/', [GalleryController::class, 'index'])->name('index');
            Route::post('/', [GalleryController::class, 'store'])->name('store');
            Route::get('/{id}', [GalleryController::class, 'show'])->name('show');
            Route::put('/{id}', [GalleryController::class, 'update'])->name('update');
            Route::delete('/{id}', [GalleryController::class, 'delete'])->name('delete');
        });
        Route::name('reviews.')->prefix('reviews')->group(function () {
            Route::get('/', [ReviewsController::class, 'index'])->name('index');
            Route::post('/', [ReviewsController::class, 'store'])->name('store');
            Route::get('/{id}', [ReviewsController::class, 'show'])->name('show');
            Route::put('/{id}', [ReviewsController::class, 'update'])->name('update');
            Route::delete('/{id}', [ReviewsController::class, 'delete'])->name('delete');
        });
    });

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/admin/contact.blade.php
@extends('adminlte::page')

@section('title', 'Контакты')

@section('content_header')
    <div class="row d-flex justify-content-between col-md">
        <div>
            <h1>Контакты</h1>
        </div>
        <div>
            <x-adminlte-button label="Создать" theme="primary" data-toggle="modal" data-target="#modalCreate"
                               icon="fa fa-lg fa-fw fa-plus">
            </x-adminlte-button>
            <x-adminlte-modal icon="fa fa-info-circle" id="modalCreate" title="Создание"
                              size='lg' v-centered static-backdrop scrollable>
                <form action="{{route('admin.contact.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="col-md-6">Тип</div>
                        <div class="col-md-6">
                        <select class="form-control" name="type" v-model="selectedType">
                            <option value="phone">Телефон</option>
                            <option value="email">Email</option>
                        </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">Данные</div>
                        <label class="col-md-6">
                            <input class="form-control" type="text" name="data"
                                   placeholder="Enter data">
                        </label>
                    </div>
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary">Создать</button>
                    </div>
                    <x-slot name="footerSlot"></x-slot>
                </form>
            </x-adminlte-modal>
        </div>
    </div>
@stop

@section('content')
    @php
        $heads = [
            'id',
            'Тип',
            'Данные',
      ];
    @endphp


    <x-adminlte-datatable id="table1" :heads="$heads" striped hoverable compressed beautify>
{{--        @if($contact)--}}
            @foreach($contact as $con)
                <tr>
                    <td>{{$con->id}}</td>
                    <td>{{$con->type}}</td>
                    <td>{{$con->data}}</td>
                    <td>
                        <x-adminlte-button theme="primary" data-toggle="modal" data-target="#modalEdit{{$con->id}}"
                                           icon="fa fa-lg fa-fw fa-pen"></x-adminlte-button>
                        <x-adminlte-button theme="danger" data-toggle="modal" data-target="#modalDelete{{$con->id}}"
                                           icon="fa fa-lg fa-fw fa-trash"></x-adminlte-button>
                        <x-adminlte-button data-toggle="modal" data-target="#modalShow{{$con->id}}"
                                           icon="fa fa-lg fa-fw fa-eye">
                        </x-adminlte-button>
                    </td>
                </tr>
                <x-adminlte-modal icon="fa fa-info-circle" id="modalShow{{$con->id}}" title="Контакт"
                                  size='lg' enctype="multipart/form-data" v-centered static-backdrop scrollable>
                    <div class="row">
                        <div class="col-md-6">ID</div>
                        <div class="col-md-6">{{$con->id}}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">Тип</div>
                        <div class="col-md-6">{{$con->type}}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">Данные</div>
                        <div class="col-md-6">{{$con->data}}</div>
                    </div>
                    <x-slot name="footerSlot"></x-slot>
                </x-adminlte-modal>
                <x-adminlte-modal theme="danger" icon="fa fa-lg fa-fw fa-trash" id="modalDelete{{$con->id}}"
                                  title="Удаление"
                                  v-centered static-backdrop scrollable>
                    Вы уверены?
                    <x-slot name="footerSlot">
                        <form action="{{ route('admin.contact.delete', ['id' => $con->id]) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <x-adminlte-button theme="success" type="submit" label="Yes"/>
                        </form>
                        <x-adminlte-button label="No" data-dismiss="modal" theme="danger"/>
                    </x-slot>
                </x-adminlte-modal>
                <x-adminlte-modal theme="primary" icon="fa fa-lg fa-fw fa-pen" id="modalEdit{{$con->id}}"
                                  title="Редактирование" size="lg"
                                  v-centered static-backdrop scrollable>
                    <form action="{{route('admin.contact.update', ['id' => $con->id])}}" method="POST"
                          enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-md-6">Тип</div>
                            <label class="col-md-6">
                                <input class="form-control" type="text" name="type"
                                       placeholder="Enter type" value="{{$con->type}}">
                            </label>
                        </div>
                        <div class="row">
                            <div class="col-md-6">Данные</div>
                            <label class="col-md-6">
                                <input class="form-control" type="text" name="data"
                                       placeholder="Enter data" value="{{$con->data}}">
                            </label>
                        </div>
                        <div class="d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">Обновить</button>
                        </div>
                        <x-slot name="footerSlot"></x-slot>
                    </form>
                </x-adminlte-modal>
            @endforeach
{{--        @endif--}}
    </x-adminlte-datatable>
@endsection

resources/views/admin/reviews.blade.php
@extends('adminlte::page')

@section('title', 'Отзывы')

@section('content_header')
    <div class="row d-flex justify-content-between col-md">
        <div>
            <h1>Отзывы</h1>
        </div>
        <div>
            <x-adminlte-button label="Создать" theme="primary" data-toggle="modal" data-target="#modalCreate"
                               icon="fa fa-lg fa-fw fa-plus">
            </x-adminlte-button>
            <x-adminlte-modal icon="fa fa-info-circle" id="modalCreate" title="Создание"
                              size='lg' v-centered static-backdrop scrollable>
                <form action="{{route('admin.reviews.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="col-md-6">Имя</div>
                        <label class="col-md-6">
                            <input class="form-control" type="text" name="name"
                                   placeholder="Enter name">
                        </label>
                    </div>
                    <div class="row">
                        <div class="col-md-6">Сообщение</div>
                        <div class="editor">
                            <textarea name="content"></textarea>
                        </div>
                    </div>
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary">Создать</button>
                    </div>
                    <x-slot name="footerSlot"></x-slot>
                </form>
            </x-adminlte-modal>
        </div>
    </div>
@stop

@section('content')
    @php
        $heads = [
            'id',
            'Имя',
            'Сообщение',
      ];
    @endphp


    <x-adminlte-datatable id="table1" :heads="$heads" striped hoverable compressed beautify>
        {{--        @if($contact)--}}
        @foreach($reviews as $rev)
            <tr>
                <td>{{$rev->id}}</td>
                <td>{{$rev->name}}</td>
                <td>{{$rev->content}}</td>
                <td>
                    <x-adminlte-button theme="primary" data-toggle="modal" data-target="#modalEdit{{$rev->id}}"
                                       icon="fa fa-lg fa-fw fa-pen"></x-adminlte-button>
                    <x-adminlte-button theme="danger" data-toggle="modal" data-target="#modalDelete{{$rev->id}}"
                                       icon="fa fa-lg fa-fw fa-trash"></x-adminlte-button>
                    <x-adminlte-button data-toggle="modal" data-target="#modalShow{{$rev->id}}"
                                       icon="fa fa-lg fa-fw fa-eye">
                    </x-adminlte-button>
                </td>
            </tr>
            <x-adminlte-modal icon="fa fa-info-circle" id="modalShow{{$rev->id}}" title="Контакт"
                              size='lg' enctype="multipart/form-data" v-centered static-backdrop scrollable>
                <div class="row">
                    <div class="col-md-6">ID</div>
                    <div class="col-md-6">{{$rev->id}}</div>
                </div>
                <div class="row">
                    <div class="col-md-6">Имя</div>
                    <div class="col-md-6">{{$rev->name}}</div>
                </div>
                <div class="row">
                    <div class="col-md-6">Сообщение</div>
                    <div class="col-md-6">{{$rev->content}}</div>
                </div>
                <x-slot name="footerSlot"></x-slot>
            </x-adminlte-modal>
            <x-adminlte-modal theme="danger" icon="fa fa-lg fa-fw fa-trash" id="modalDelete{{$rev->id}}"
                              title="Удаление"
                              v-centered static-backdrop scrollable>
                Вы уверены?
                <x-slot name="footerSlot">
                    <form action="{{ route('admin.reviews.delete', ['id' => $rev->id]) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <x-adminlte-button theme="success" type="submit" label="Да"/>
                    </form>
                    <x-adminlte-button label="Нет" data-dismiss="modal" theme="danger"/>
                </x-slot>
            </x-adminlte-modal>
            <x-adminlte-modal theme="primary" icon="fa fa-lg fa-fw fa-pen" id="modalEdit{{$rev->id}}"
                              title="Редактирование" size="lg"
                              v-centered static-backdrop scrollable>
                <form action="{{route('admin.reviews.update', ['id' => $rev->id])}}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="row">
                        <div class="col-md-6">Имя</div>
                        <label class="col-md-6">
                            <input class="form-control" type="text" name="name"
                                   placeholder="Enter type" value="{{$rev->name}}">
                        </label>
                    </div>
                    <div class="row">
                        <div class="col-md-6">Сообщение</div>
                        <div class="editor">
                            <textarea name="content">{{$rev->content}}</textarea>
                        </div>
                    </div>
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary">Обновить</button>
                    </div>
                    <x-slot name="footerSlot"></x-slot>
                </form>
            </x-adminlte-modal>
        @endforeach
        {{--        @endif--}}
    </x-adminlte-datatable>
    {{$reviews->links('pagination::bootstrap-4')}}
@endsection

resources/views/admin/services.blade.php
@extends('adminlte::page')

@section('title', 'Услуги')

@section('content_header')
    <div class="row d-flex justify-content-between col-md">
        <div>
            <h1>Услуги</h1>
        </div>
        <div>
            <x-adminlte-button label="Создать" theme="primary" data-toggle="modal" data-target="#modalCreate"
                               icon="fa fa-lg fa-fw fa-plus">
            </x-adminlte-button>
            <x-adminlte-modal icon="fa fa-info-circle" id="modalCreate" title="Создание"
                              size='lg' v-centered static-backdrop scrollable>
                <form action="{{route('admin.services.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="col-md-6">Название услуги</div>
                        <label class="col-md-6">
                            <input class="form-control" type="text" name="title"
                                   placeholder="Enter title">
                        </label>
                    </div>
                    <div class="row">
                        <div class="col-md-6">Картинка</div>
                        <label class="col-md-6">
                            <input class="form-control" type="file" name="image"
                                   placeholder="Enter image" accept="image/*">
                        </label>
                    </div>
                    <div class="row">
                        <div class="col-md-6">Описание услуги</div>
                        <label class="col-md-6">
                            <div class="editor">
                                <textarea name="content"></textarea>
                            </div>
                        </label>
                    </div>
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary">Создать</button>
                    </div>
                    <x-slot name="footerSlot"></x-slot>
                </form>
            </x-adminlte-modal>
        </div>
    </div>
@stop

@section('content')
    @php
        $heads = [
            'id',
            'Название',
            'Описание',
            'Картинка',
      ];
    @endphp


    <x-adminlte-datatable id="table1" :heads="$heads" striped hoverable compressed beautify>
        {{--        @if($contact)--}}
        @foreach($services as $ser)
            <tr>
                <td>{{$ser->id}}</td>
                <td>{{$ser->title}}</td>
                <td>{{$ser->content}}</td>
                <td><img width="150px" src="{{$ser->image}}" alt=""></td>
                <td>
                    <x-adminlte-button theme="primary" data-toggle="modal" data-target="#modalEdit{{$ser->id}}"
                                       icon="fa fa-lg fa-fw fa-pen"></x-adminlte-button>
                    <x-adminlte-button theme="danger" data-toggle="modal" data-target="#modalDelete{{$ser->id}}"
                                       icon="fa fa-lg fa-fw fa-trash"></x-adminlte-button>
                    <x-adminlte-button data-toggle="modal" data-target="#modalShow{{$ser->id}}"
                                       icon="fa fa-lg fa-fw fa-eye">
                    </x-adminlte-button>
                </td>
            </tr>
            <x-adminlte-modal icon="fa fa-info-circle" id="modalShow{{$ser->id}}" title="Контакт"
                              size='lg' enctype="multipart/form-data" v-centered static-backdrop scrollable>
                <div class="row">
                    <div class="col-md-6">ID</div>
                    <div class="col-md-6">{{$ser->id}}</div>
                </div>
                <div class="row">
                    <div class="col-md-6">Название</div>
                    <div class="col-md-6">{{$ser->title}}</div>
                </div>
                <div class="row">
                    <div class="col-md-6">Описание</div>
                    <div class="col-md-6">{{$ser->content}}</div>
                </div>
                <x-slot name="footerSlot"></x-slot>
            </x-adminlte-modal>
            <x-adminlte-modal theme="danger" icon="fa fa-lg fa-fw fa-trash" id="modalDelete{{$ser->id}}"
                              title="Удаление"
                              v-centered static-backdrop scrollable>
                Вы уверены?
                <x-slot name="footerSlot">
                    <form action="{{ route('admin.services.delete', ['id' => $ser->id]) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <x-adminlte-button theme="success" type="submit" label="Yes"/>
                    </form>
                    <x-adminlte-button label="No" data-dismiss="modal" theme="danger"/>
                </x-slot>
            </x-adminlte-modal>
            <x-adminlte-modal theme="primary" icon="fa fa-lg fa-fw fa-pen" id="modalEdit{{$ser->id}}"
                              title="Редактирование" size="lg"
                              v-centered static-backdrop scrollable>
                <form action="{{route('admin.services.update', ['id' => $ser->id])}}" method="POST"
                      enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="row">
                        <div class="col-md-6">Название</div>
                        <label class="col-md-6">
                            <input class="form-control" type="text" name="title"
                                   placeholder="Enter title" value="{{$ser->title}}">
                        </label>
                    </div>
                    <div class="row">
                        <div class="col-md-6">Картинка</div>
                        <label class="col-md-6">
                            <input class="form-control" type="file" name="image"
                                   placeholder="Enter image" accept="image/*" aria-label="{{$ser->image}}">
                        </label>
                    </div>
                    <div class="row">
                        <div class="col-md-6">Описание</div>
                        <div class="editor">
                            <textarea name="content">{{$ser->content}}</textarea>
                        </div>
                    </div>
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary">Обновить</button>
                    </div>
                    <x-slot name="footerSlot"></x-slot>
                </form>
            </x-adminlte-modal>
        @endforeach
        {{--        @endif--}}
    </x-adminlte-datatable>
    {{$services->links('pagination::bootstrap-4')}}
@endsection

resources/views/home.blade.php
@extends('adminlte::page')

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>